### ISSUE TITLE
Error when running Docker image

### ISSUE THREAD

**Issue by bgoerz** [xperimental/netatmo-exporter#14]
**I tried this** 

```
netatmo-exporter:
    container_name: netatmo-exporter
    image: xperimental/netatmo-exporter:latest
    ports:
      - "9210:9210"
    environment:
      - NETATMO_EXPORTER_ADDR=IP-ADRESS_of_DOCKER_HOST
      - NETATMO_CLIENT_ID=NETATMO_DEV-ID
      - NETATMO_CLIENT_SECRET=NETATMO_DEV-SECRET
      - NETATMO_CLIENT_USERNAME=NETATMO_USER_MAIL-ADDRESS
      - NETATMO_CLIENT_PASSWORD=NETATMO_USER_PASSWORD
    restart: unless-stopped
```

and after starting the container I'll get this in the logs
sudo docker container logs -f --details netatmo-exporter
 standard_init_linux.go:207: exec user process caused "exec format error"
 standard_init_linux.go:207: exec user process caused "exec format error"
 standard_init_linux.go:207: exec user process caused "exec format error"
 standard_init_linux.go:207: exec user process caused "exec format error"
 standard_init_linux.go:207: exec user process caused "exec format error"

Any help would be appreciated
