### ISSUE TITLE
Error creating client: oauth2: cannot fetch token: 400\nResponse: {\"error\":\"invalid_client\"}

### ISSUE THREAD

**Issue by QuiiBz** [xperimental/netatmo-exporter#25]
Hi, I have an error when running this exporter. I created an app in Netatmo developer portal, copied the client and secret id, and copied my username and password and I still get this "invalid_client" error.

The credentials are the right ones, I checked multiple times. I also tried to create another app and activate/deactivate the app, but still had the same error. 

Here's the full docker-compose service:
```yaml
netatmo-exporter:
  image: xperimental/netatmo-exporter
  container_name: netatmo-exporter
  restart: unless-stopped
  ports:
    - 9210:9210
  environment:
    - NETATMO_CLIENT_ID='clientid'
    - NETATMO_CLIENT_SECRET='clientsecret'
    - NETATMO_CLIENT_USERNAME='username'
    - NETATMO_CLIENT_PASSWORD='password'
  networks:
    - proxy
```
